import { DomainError } from '../errors/DomainError.js';

/**
 * ToDoList Entity - Represents a list of to-do items
 * 
 * This entity groups related to-do items together (e.g., "Home Chores", "Work Tasks").
 * It enforces business rules for list titles.
 * 
 * Business Rules:
 * - Title is required and cannot be empty
 * - Title must not exceed 100 characters
 */
export class ToDoList {
  /**
   * Creates a ToDoList instance
   * @param {Object} params - ToDoList parameters
   * @param {string} params.id - Unique identifier
   * @param {string} params.title - List title
   * @param {string} params.userId - ID of the user who owns this list
   * @param {Date} [params.createdAt] - Creation timestamp
   * @param {Date} [params.updatedAt] - Last update timestamp
   */
  constructor({ id, title, userId, createdAt, updatedAt }) {
    this.id = id;
    this.title = title;
    this.userId = userId;
    this.createdAt = createdAt || new Date();
    this.updatedAt = updatedAt || new Date();
    
    // Validate on construction
    this.validateTitle();
  }

  /**
   * Validates the title according to business rules
   * @throws {DomainError} If title is invalid
   */
  validateTitle() {
    if (!this.title || typeof this.title !== 'string') {
      throw new DomainError('Title is required and must be a string');
    }
    
    const trimmedTitle = this.title.trim();
    
    if (trimmedTitle.length === 0) {
      throw new DomainError('Title cannot be empty');
    }
    
    if (trimmedTitle.length > 100) {
      throw new DomainError('Title must not exceed 100 characters');
    }
  }

  /**
   * Factory method to create a new ToDoList
   * @param {string} title - List title
   * @param {string} userId - Owner user ID
   * @param {string} [id] - Optional ID (will be generated by repository if not provided)
   * @returns {ToDoList} New ToDoList instance
   */
  static create(title, userId, id = null) {
    return new ToDoList({
      id,
      title: title.trim(),
      userId,
      createdAt: new Date(),
      updatedAt: new Date()
    });
  }

  /**
   * Updates the title of the list
   * @param {string} newTitle - New title
   */
  updateTitle(newTitle) {
    this.title = newTitle.trim();
    this.updatedAt = new Date();
    this.validateTitle();
  }

  /**
   * Converts the ToDoList entity to a plain object
   * @returns {Object} Plain object representation
   */
  toJSON() {
    return {
      id: this.id,
      title: this.title,
      userId: this.userId,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    };
  }
}

