import { DomainError } from '../errors/DomainError.js';

/**
 * User Entity - Represents a user in the system
 * 
 * This is a core domain entity that encapsulates user data and validation logic.
 * It has no dependencies on external frameworks or databases (Clean Architecture principle).
 * 
 * Business Rules:
 * - Email must be in valid format
 * - Email must be unique (validated at repository level)
 */
export class User {
  /**
   * Creates a User instance
   * @param {Object} params - User parameters
   * @param {string} params.id - Unique identifier
   * @param {string} params.email - User email address
   * @param {string} params.passwordHash - Hashed password
   * @param {Date} [params.createdAt] - Creation timestamp
   * @param {Date} [params.updatedAt] - Last update timestamp
   */
  constructor({ id, email, passwordHash, createdAt, updatedAt }) {
    this.id = id;
    this.email = email;
    this.passwordHash = passwordHash;
    this.createdAt = createdAt || new Date();
    this.updatedAt = updatedAt || new Date();
    
    // Validate on construction
    this.validateEmail();
  }

  /**
   * Validates email format using regex
   * @throws {DomainError} If email format is invalid
   */
  validateEmail() {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    
    if (!this.email || typeof this.email !== 'string') {
      throw new DomainError('Email is required and must be a string');
    }
    
    if (!emailRegex.test(this.email)) {
      throw new DomainError('Email format is invalid');
    }
  }

  /**
   * Factory method to create a new User
   * @param {string} email - User email
   * @param {string} passwordHash - Hashed password
   * @param {string} [id] - Optional ID (will be generated by repository if not provided)
   * @returns {User} New User instance
   */
  static create(email, passwordHash, id = null) {
    return new User({
      id,
      email: email.toLowerCase().trim(), // Normalize email
      passwordHash,
      createdAt: new Date(),
      updatedAt: new Date()
    });
  }

  /**
   * Converts the User entity to a plain object (without passwordHash for security)
   * @returns {Object} Plain object representation
   */
  toJSON() {
    return {
      id: this.id,
      email: this.email,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    };
  }
}

